name = "EasyFit"
uuid = "fde71243-0cda-4261-b7c7-4845bd106b21"
authors = ["Leandro Martinez <leandro@iqm.unicamp.br>"]
version = "0.1.0"

[compat]
julia = "1"
LsqFit = "0.11.0"
Interpolations = "0.12.10"

